
   platform :ios, '8.0'
   pod 'AFNetworking', '~> 3.0.4'
   pod 'MJExtension', '~> 3.0.10'
   pod 'SDWebImage', '~> 3.7.4'
   pod 'SVProgressHUD', '~> 2.0-beta3'
   pod 'Masonry', '~> 0.6.4'
   pod 'MJRefresh', '~> 3.1.0'


   pod 'DACircularProgress', '~> 2.3.1'
